### ISSUE TITLE
uuid bug cause

### ISSUE THREAD

**Issue by Tsumiki129** [AnonymousHacker1279/ImmersiveWeapons#105]
hi i have found na bug were the mod will creat a uuid bug by adding an emptie tag and wen placed and then broken for items such as torches it removes this added tad making the items not stack corectly.
forge 47.1.3
 version 1.20.1
not crashing game just annoying bug

**Comment by AnonymousHacker1279** [comment]
Can you provide more information? In what context does this occur? I'm not aware of any random empty tags being added to items.

**Comment by Tsumiki129** [comment]
its happens in survival at times but was very repeated in creative wen checking the items uuid after spawning in some torches and checking there uuid they would have an extra tag on the end  after placing and braking that tag would be removed i picked apart the mod list i have and the moment i came to this mod and added it the uuid mismatch tag showed up i used the comad to get the uuid of the torch it also affects redstone and i had it happen to ae2 mod item 

/data get entity @p SelectedItem

![immersive weapons bug](https://github.com/AnonymousHacker1279/ImmersiveWeapons/assets/147937268/3ba9f8b3-76fc-4aeb-9b45-fd6bc2f762e6)

**Comment by AnonymousHacker1279** [comment]
I found an easy way to reproduce it: 
- `/give @s minecraft:torch 2`
- `/data get entity @s SelectedItem` -> no empty tag added
- Open inventory and split the stack in half
- `/data get entity @s SelectedItem` -> empty tag added

It should be fixed in the latest commit. If you would like to build and test it yourself, please use the [1.20.1-dev](https://github.com/AnonymousHacker1279/ImmersiveWeapons/tree/1.20.1-dev) branch. Otherwise, I should hopefully have a new release out within a few days.

Fixed by af4bcd53.
